<?php 
session_start();
if(isset($_SESSION['uname'])){
    session_destroy();
    header('Location:index.php');
    die();
}
else{
    session_destroy();
    header('Location:index.php');
    die();    
}
mysqli_close($conn);
?>